# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.caleb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# mandatory
---

# for docker

spring:
  datasource:
    #using jdbc, java database
    url: jdbc:mysql://mysql1/inventory-db
    username: user
    password: pwd

  jpa:
    hibernate:
      ddl-auto: none

  config:
    activate:
      on-profile: docker

  # telling it to go look for script file
  sql:
    init:
      platform: mysql
      mode: always

server.port: 8080

---

# for test

#for h2
spring:
  config:
    activate:
      on-profile: h2

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:inventory-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      #let jpa create the schema

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true

    #defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      mode: always

# telling it when to timeout
spring.datasource.hikari.initializationFailTimeout: 60000